TeamOpenIndustry/ImmersiveRailroading

- src/main/java/cam72cam/immersiverailroading/entity/EntityRollingStock.java
- src/main/java/cam72cam/immersiverailroading/registry/EntityRollingStockDefinition.java
- src/main/resources/assets/immersiverailroading/rolling_stock/freight/boxcar_us.json
- src/main/resources/assets/immersiverailroading/rolling_stock/freight/flatcar_us.json
- src/main/resources/assets/immersiverailroading/rolling_stock/locomotives/a1_peppercorn.json
- src/main/resources/assets/immersiverailroading/rolling_stock/locomotives/big_boy.json
- src/main/resources/assets/immersiverailroading/rolling_stock/locomotives/gp-7.json
- src/main/resources/assets/immersiverailroading/rolling_stock/passenger/br_coach_mk1.json
- src/main/resources/assets/immersiverailroading/rolling_stock/tank/tank_us.json
- src/main/resources/assets/immersiverailroading/rolling_stock/tender/a1_peppercorn_tender.json
updated JSON files with realistic weights and updated EntityRollingStock to pull the weight from the JSONs.
in response to #19
> Added weight to the locos, tenders, and cars

- MODEL_LICENSE
> Update Model License

- src/main/java/cam72cam/immersiverailroading/registry/CarFreightDefinition.java
- src/main/java/cam72cam/immersiverailroading/render/entity/StockModel.java
> support rendering only the current cargo load

- src/main/java/cam72cam/immersiverailroading/Config.java
- src/main/java/cam72cam/immersiverailroading/entity/LocomotiveSteam.java
#284  can be closed and moved to DONE in the "2.0 Release" Project.
> Added config option to disable env. Damage on Boiler Explosion (added #284)

- src/main/java/cam72cam/immersiverailroading/Config.java
Added Support for "Naphtha" and "Refined Fuel". Are the values that I gave them good?
--> #302
> Added Support for Thermal Foundation/Expansion Fuels

- .travis.yml
- README.md
The actual Readme.md wasn't updated for a year and is really outdated, so I thought making a new one. Would it be possible to activate the widget setting on the Discord server and adding the badge plugin to the Jenkins server, to get all the badges to work?
> Better readme? [Needs Review, because my english is not the best]

- src/main/resources/assets/immersiverailroading/rolling_stock/tender/big_boy_tender.json
Light weight recalculated. Minor change. Water Capacity decreased slightly. Coal Capacity halved, it was 56 ton, now 28 ton.
> Minor Adjustments

- src/main/resources/assets/immersiverailroading/rolling_stock/tender/k36_tender.json
Lt weight reduced. Nothing else altered.
> Lt Weight Adjustment

- src/main/resources/assets/immersiverailroading/rolling_stock/locomotives/a5_switcher.json
72mph for an 0-4-0? Revised to 30mph..... Increased Tractive Effort, Decreased Horsepower.
> Speed and Power Revisions

- src/main/resources/assets/immersiverailroading/rolling_stock/locomotives/skookum.json
Weight of engine was nearly half of what it should be. Revised to 64,410kg. Should help with Tractive Effort issues.
> Update Skookum Json - Engine Weight Correction.

- src/main/java/cam72cam/immersiverailroading/gui/FreightContainer.java
> Add support for inventory tweaks.

- AUTHORS
- src/main/java/cam72cam/immersiverailroading/thirdparty/opencomputers/AugmentDriver.java
couldn't figure out how to change the other one, sorry
> Updated OC Consist info get

- build.gradle
- src/main/java/cam72cam/immersiverailroading/IRItems.java
- src/main/java/cam72cam/immersiverailroading/blocks/BlockRailBase.java
- src/main/java/cam72cam/immersiverailroading/items/ItemSwitchHammer.java
- src/main/java/cam72cam/immersiverailroading/proxy/ClientProxy.java
- src/main/java/cam72cam/immersiverailroading/proxy/CommonProxy.java
- src/main/java/cam72cam/immersiverailroading/tile/TileRail.java
- src/main/java/cam72cam/immersiverailroading/tile/TileRailBase.java
- src/main/java/cam72cam/immersiverailroading/track/BuilderCubicCurve.java
- src/main/java/cam72cam/immersiverailroading/util/RailInfo.java
- src/main/java/cam72cam/immersiverailroading/util/SwitchUtil.java
- src/main/resources/assets/immersiverailroading/lang/en_US.lang
- src/main/resources/assets/immersiverailroading/recipes/switch hammer.json
- src/main/resources/assets/immersiverailroading/recipes/switch hammer_iron.json
- src/main/resources/assets/immersiverailroading/wiki/en_us/casting-basin.txt
- src/main/resources/assets/immersiverailroading/wiki/en_us/resource-packs-(outside-sources).txt
- src/main/resources/assets/immersiverailroading/wiki/en_us/steam-hammer.txt
- src/main/resources/assets/immersiverailroading/wiki/en_us/track-roller.txt
Implements #510 , but at the moment it doesn't work.
> Switch toggle item

- src/main/java/cam72cam/immersiverailroading/entity/EntityRollingStock.java
- src/main/java/cam72cam/immersiverailroading/library/ChatText.java
- src/main/resources/assets/immersiverailroading/lang/de_DE.lang
- src/main/resources/assets/immersiverailroading/lang/en_US.lang
- src/main/resources/assets/immersiverailroading/rolling_stock/locomotives/alco_rs1.json
Stock now tells you when it has no variants so players know that the
brush is actually still working.
> Added text feedback for paintbrush

- src/main/java/cam72cam/immersiverailroading/Config.java
- src/main/java/cam72cam/immersiverailroading/gui/CastingGUI.java
- src/main/java/cam72cam/immersiverailroading/gui/GuiScrollBar.java
- src/main/java/cam72cam/immersiverailroading/gui/ItemPickerGUI.java
- src/main/java/cam72cam/immersiverailroading/gui/PlateRollerGUI.java
- src/main/java/cam72cam/immersiverailroading/library/Gauge.java
Addresses [Config option for restricting stock to intended gauge](https://github.com/cam72cam/ImmersiveRailroading/issues/266)
"Model" gauges is defined by Gauge.isModel(gauge)
> Restrict building stock to only recommended and model gauges

- src/main/java/cam72cam/immersiverailroading/multiblock/RailRollerMultiblock.java
39ft sticks are standard, 39ft = 11.88m, rounded that up to 12.
> Output Increase

- .github/ISSUE_TEMPLATE/suggestion.md
Update the suggestion template
> Suggestion Template Update

- src/main/java/cam72cam/immersiverailroading/ImmersiveRailroading.java
- src/main/java/cam72cam/immersiverailroading/render/item/ObjItemRender.java
- src/main/java/cam72cam/immersiverailroading/render/item/PlateItemModel.java
- src/main/java/cam72cam/immersiverailroading/render/item/RailAugmentItemModel.java
- src/main/java/cam72cam/immersiverailroading/render/item/RailCastItemRender.java
- src/main/java/cam72cam/immersiverailroading/render/item/RailItemRender.java
- src/main/java/cam72cam/immersiverailroading/render/item/StockItemComponentModel.java
- src/main/java/cam72cam/immersiverailroading/render/item/StockItemModel.java
- src/main/java/cam72cam/immersiverailroading/render/item/TrackBlueprintItemModel.java
Depends on https://github.com/TeamOpenIndustry/UniversalModCore/pull/5
> Switch to new item render API

- src/main/resources/assets/immersiverailroading/lang/ru_RU.lang
> Rus translate update 1.7.3

- src/main/java/cam72cam/immersiverailroading/library/CouplerAugmentMode.java
- src/main/java/cam72cam/immersiverailroading/library/LocoControlMode.java
- src/main/java/cam72cam/immersiverailroading/library/RedstoneMode.java
- src/main/java/cam72cam/immersiverailroading/library/StockDetectorMode.java
- src/main/java/cam72cam/immersiverailroading/tile/TileRailBase.java
- src/main/resources/assets/immersiverailroading/lang/en_US.lang
> Make loader augments redstone controlled

- src/main/java/cam72cam/immersiverailroading/ImmersiveRailroading.java
- src/main/java/cam72cam/immersiverailroading/entity/EntityMoveableRollingStock.java
- src/main/java/cam72cam/immersiverailroading/registry/TrackDefinition.java
- src/main/java/cam72cam/immersiverailroading/tile/TileRail.java
- src/main/java/cam72cam/immersiverailroading/tile/TileRailBase.java
> Add support for disabling clacking in track definitions

- AUTHORS
- src/main/java/cam72cam/immersiverailroading/Config.java
- src/main/java/cam72cam/immersiverailroading/tile/TileRailBase.java
- add debug option to automatically switch newly placed augments into computer mode
> feat: add config for default augment modes

- src/main/java/cam72cam/immersiverailroading/entity/EntityRidableRollingStock.java
- src/main/java/cam72cam/immersiverailroading/entity/FreightTank.java
- src/main/java/cam72cam/immersiverailroading/gui/TrackGui.java
- src/main/java/cam72cam/immersiverailroading/items/ItemTrackBlueprint.java
- src/main/java/cam72cam/immersiverailroading/items/nbt/RailSettings.java
- src/main/java/cam72cam/immersiverailroading/render/block/RailBaseModel.java
- src/main/java/cam72cam/immersiverailroading/render/item/TrackBlueprintItemModel.java
- src/main/java/cam72cam/immersiverailroading/render/item/TrackExchangerModel.java
- src/main/java/cam72cam/immersiverailroading/tile/TileMultiblock.java
- src/main/java/cam72cam/immersiverailroading/tile/TileRail.java
- src/main/java/cam72cam/immersiverailroading/tile/TileRailBase.java
- src/main/java/cam72cam/immersiverailroading/tile/TileRailPreview.java
- src/main/java/cam72cam/immersiverailroading/track/BuilderCrossing.java
- src/main/java/cam72cam/immersiverailroading/track/BuilderCubicCurve.java
- src/main/java/cam72cam/immersiverailroading/track/BuilderSwitch.java
- src/main/java/cam72cam/immersiverailroading/track/BuilderTurnTable.java
- src/main/java/cam72cam/immersiverailroading/util/RailInfo.java
My evil wizard powers are not effective in newer java versions...
> Remove serializing into final java fields

- src/main/java/cam72cam/immersiverailroading/entity/CarPassenger.java
- src/main/java/cam72cam/immersiverailroading/entity/Freight.java
- src/main/java/cam72cam/immersiverailroading/registry/CarFreightDefinition.java
- src/main/java/cam72cam/immersiverailroading/registry/CarPassengerDefinition.java
> Allow passenger cars to carry cargo (if defined in json)

- caml.py
- src/main/java/cam72cam/immersiverailroading/Config.java
- src/main/java/cam72cam/immersiverailroading/gui/overlay/CAML.java
- src/main/java/cam72cam/immersiverailroading/gui/overlay/DataBlock.java
- src/main/java/cam72cam/immersiverailroading/gui/overlay/GuiBuilder.java
- src/main/java/cam72cam/immersiverailroading/items/ItemLargeWrench.java
- src/main/java/cam72cam/immersiverailroading/library/ValveGearConfig.java
- src/main/java/cam72cam/immersiverailroading/model/TrackModel.java
- src/main/java/cam72cam/immersiverailroading/model/part/Whistle.java
- src/main/java/cam72cam/immersiverailroading/registry/CarFreightDefinition.java
- src/main/java/cam72cam/immersiverailroading/registry/CarPassengerDefinition.java
- src/main/java/cam72cam/immersiverailroading/registry/CarTankDefinition.java
- src/main/java/cam72cam/immersiverailroading/registry/DefinitionManager.java
- src/main/java/cam72cam/immersiverailroading/registry/EntityRollingStockDefinition.java
- src/main/java/cam72cam/immersiverailroading/registry/FreightDefinition.java
- src/main/java/cam72cam/immersiverailroading/registry/HandCarDefinition.java
- src/main/java/cam72cam/immersiverailroading/registry/LocomotiveDefinition.java
- src/main/java/cam72cam/immersiverailroading/registry/LocomotiveDieselDefinition.java
- src/main/java/cam72cam/immersiverailroading/registry/LocomotiveSteamDefinition.java
- src/main/java/cam72cam/immersiverailroading/registry/Quilling.java
- src/main/java/cam72cam/immersiverailroading/registry/TenderDefinition.java
- src/main/java/cam72cam/immersiverailroading/registry/TrackDefinition.java
- src/main/java/cam72cam/immersiverailroading/tile/TileRail.java
- src/main/java/cam72cam/immersiverailroading/util/CAML.java
- src/main/java/cam72cam/immersiverailroading/util/DataBlock.java
- src/main/java/cam72cam/immersiverailroading/util/JSON.java
- src/main/java/cam72cam/immersiverailroading/util/MathUtil.java
> Caml support

- src/main/java/cam72cam/immersiverailroading/physics/MovementTrack.java
- src/main/java/cam72cam/immersiverailroading/tile/TileRailBase.java
- src/main/java/cam72cam/immersiverailroading/track/IIterableTrack.java
- src/main/java/cam72cam/immersiverailroading/util/SwitchUtil.java
- replace some distanceTo calls with distanceToSquared where possible for slight physics performance increase
(related to #1368)
> perf: physic performance improvements

- src/main/java/cam72cam/immersiverailroading/tile/TileRailBase.java
This is an alternate idea to https://github.com/TeamOpenIndustry/ImmersiveRailroading/pull/1298
> Add push-pull mode to item/fluid augments

- src/main/java/cam72cam/immersiverailroading/multiblock/Multiblock.java
By using parallel stream this pr optimizes multiblock `tryCreate` method by about 50%
Also improves some grammar expression
> [Feature]Optimize multiblock creation

- src/main/java/cam72cam/immersiverailroading/model/animation/StockAnimation.java
- src/main/java/cam72cam/immersiverailroading/registry/EntityRollingStockDefinition.java
Add `range_min` and `range_max` in animatrix definition for better value mapping, following what [Readout.java](https://github.com/TeamOpenIndustry/ImmersiveRailroading/blob/master/src/main/java/cam72cam/immersiverailroading/model/part/Readout.java) has
> [Feature] Add range property to animatrix definition for better mapping

- src/main/java/cam72cam/immersiverailroading/entity/EntityMoveableRollingStock.java
- src/main/java/cam72cam/immersiverailroading/registry/EntityRollingStockDefinition.java
- src/main/java/cam72cam/immersiverailroading/tile/TileRailBase.java
- src/main/resources/assets/immersiverailroading/rolling_stock/default/base.caml
Allows modelers to set how many snow layers should be left uncleared. 
First time working on a public codebase so feel free to criticize
> snowLayers property for rolling stock

- src/main/java/cam72cam/immersiverailroading/tile/TileRailBase.java
- src/main/java/cam72cam/immersiverailroading/track/BuilderSlope.java
higher or lower than the starting block
> Allow golden spike to modify slope height

- src/main/java/cam72cam/immersiverailroading/Config.java
- src/main/java/cam72cam/immersiverailroading/entity/physics/SimulationState.java
- src/main/java/cam72cam/immersiverailroading/util/BlockUtil.java
Resolves #1427 
This PR adds a config entry to mark certain types of block undestroyable by train
> feat: add `whitelistBlocks` to prevent destruction to certain blocks

- src/main/java/cam72cam/immersiverailroading/track/BuilderCubicCurve.java
- src/main/java/cam72cam/immersiverailroading/track/BuilderIterator.java
Fixes a fatal issue introduced in #1548
> [Fix] Track won't work on long segment

- DevelopmentNotes/immersiverailroading-1.11.md
Based on commit history since 1.10.0 release
> [Docs] Update changelog
