src/main/java/cam72cam/immersiverailroading/model/obj/Face.java, src/main/java/cam72cam/immersiverailroading/model/obj/OBJModel.java, src/main/java/cam72cam/immersiverailroading/model/obj/Vec2f.java, src/main/java/cam72cam/immersiverailroading/registry/EntityRollingStockDefinition.java
The Vec2f allocation reduction saves ~50MB, the String interning saves ~200KB. The amount of non-zero UV offset Vec2f is so small as to not be worth reducing further.
Unfortunately, the mod's models still consume about 200MB even with the reduction. The format should probably be optimized for memory usage further.
=> reduce Vec2f and String allocations in model.obj

src/main/resources/assets/immersiverailroading/rolling_stock/tender/e6_tender.json
Water Capacity Unchanged. Coal Capacity was way too high, reduced. Tender Light weight reduced to 37ton. (That may be a lil high even yet.)
=> Weight and Capacity

src/main/resources/assets/immersiverailroading/rolling_stock/tender/k4_tender.json
Original Water and LT Weight figures reflect AS DELIVERED tender specs, which are NOT for the tender that is modeled here. This model is the new PRR standard Short Haul Tender and has different weight and capacities. Tender Light Weight Reduced by OVER half. Water Capacity Increased. Coal capacity decreased to reflect Short Haul 17.5 US Ton Capacity.
=> Weight and Capacities

src/main/resources/assets/immersiverailroading/rolling_stock/tender/a5_tender.json
Empty weight Decreased. Water Capacity Increased. Coal Capacity Decreased. Overall Loaded weight should decrease allowing the A5 to perform better.
=> Weight and Capacity adjustments

src/main/resources/assets/immersiverailroading/rolling_stock/tender/rodgers_460_tender.json
Water Capacity increased slightly. Coal Capacity Decreased (was way too high). Heavily Decreased Tender Empty Weight.
=> Tender Capacities and Light Weight

src/main/resources/assets/immersiverailroading/rolling_stock/tender/skookum_tender.json
Empty weight was a little heavy, reduced. Coal Capacity was over by almost 20 ton, Reduced to 10 slots. Loaded Tender weight should be closer to actual which is 40ton. (Though I'm not sure how the mod translates Buckets into kg).
=> Update Skookum Tender - Empty Weight and Coal Capacity

src/main/java/cam72cam/immersiverailroading/util/SwitchUtil.java
This fixes switches not picking up redstone in the proper spot by offsetting where the redstone detection origin is.
0 degree and 45 degree tracks will not be affected by the change.
Noted that there is a rendering error for switches facing left in any direction that is not equal to 0.
=> Fix for 22.5 angled switches not registering redstone

src/main/java/cam72cam/immersiverailroading/proxy/CommonProxy.java
Recipe uses oredict, thus does not matter if OC doesn't exist.
OC needs to be loaded before IR for this check to work properly, which is unnecessary trouble.
=> Remove OC check

src/main/java/cam72cam/immersiverailroading/entity/EntityMoveableRollingStock.java, src/main/java/cam72cam/immersiverailroading/util/IConditionalCollision.java
For a mod I'm making, I have a block that can be placed near a track. Normally the train would not hit this block, but if the train goes through a tight turn the block might be in the way of the train.
This PR adds the ability for blocks to skip collision checking with rolling stock so that those blocks do not get destroyed.
https://i.imgur.com/Iw9sRqF.png
I would love to hear your thoughts on this problem and this solution.
=> New IConditionalCollision interface that lets blocks decide whether to allow collision

src/main/java/cam72cam/immersiverailroading/multiblock/CastingMultiblock.java
The steel ingot and steel block cast out of the casting basin do not stack with the same items acquired elsewhere because an empty tag compound is applied to the item. This clears the tag compound if it is empty right before placing the item into the casting basin output title entity container.
=> Remove empty tag compound so items stack

src/main/resources/assets/immersiverailroading/lang/ru_RU.lang
An update of the Russian translation aimed at a correct interpretation of the concepts. With this version, reading and understanding what type of track you have chosen, what model or colouring of wagon you have set up will become a lot easier, as many misinterpretations that were naming things quite differently from what they should have been called have been corrected.
=> Update ru_RU.lang (fix)

src/main/java/cam72cam/immersiverailroading/entity/Locomotive.java, src/main/java/cam72cam/immersiverailroading/entity/LocomotiveSteam.java, src/main/java/cam72cam/immersiverailroading/registry/LocomotiveSteamDefinition.java
This allows any existing locomotive's controls and tender connection to be reversed.  Eventually I want to make the animation system handle this alone, but for now this is a pretty small change and is easy to support.
=> Add cab forward support

src/main/java/cam72cam/immersiverailroading/library/ModelComponentType.java, src/main/java/cam72cam/immersiverailroading/model/FreightModel.java, src/main/java/cam72cam/immersiverailroading/model/LocomotiveModel.java, src/main/java/cam72cam/immersiverailroading/model/part/CargoFill.java, src/main/java/cam72cam/immersiverailroading/model/part/CargoItems.java
Fixes #8
Re-renders every 2 seconds (instead of every frame) to reduce lag.
Implemented in model as CARGO_ITEMS_#ID# as a box that will not be rendered.  Adding STRETCHED to the group name will force the items to fill the area exactly (instead of snapping to the nearest cubic size)
=> Dynamic cargo render

AUTHORS, src/main/java/cam72cam/immersiverailroading/model/DieselLocomotiveModel.java, src/main/java/cam72cam/immersiverailroading/model/part/PartSound.java, src/main/java/cam72cam/immersiverailroading/registry/LocomotiveDieselDefinition.java, src/main/java/cam72cam/immersiverailroading/render/ExpireableMap.java
PartSound now has support for a start clip and (tentatively awaiting implementation) an end clip. New sound tag in json "start" which will play before the main engine loop upon starting a locomotive if present. I decided against making the start sound a default because even if you could find a good CC-free sound, it wouldn't sound good mixed with other pack's custom engine sounds, so it will be something modelers have to add themselves.
=> Diesel Startup Sound

src/main/java/cam72cam/immersiverailroading/ConfigSound.java, src/main/java/cam72cam/immersiverailroading/ImmersiveRailroading.java, src/main/java/cam72cam/immersiverailroading/entity/EntityCoupleableRollingStock.java, src/main/java/cam72cam/immersiverailroading/entity/EntityMoveableRollingStock.java, src/main/java/cam72cam/immersiverailroading/entity/EntityRollingStock.java, src/main/java/cam72cam/immersiverailroading/items/ItemConductorWhistle.java, src/main/java/cam72cam/immersiverailroading/library/Gauge.java, src/main/java/cam72cam/immersiverailroading/model/DieselLocomotiveModel.java, src/main/java/cam72cam/immersiverailroading/model/SteamLocomotiveModel.java, src/main/java/cam72cam/immersiverailroading/model/part/Bell.java, src/main/java/cam72cam/immersiverailroading/model/part/Control.java, src/main/java/cam72cam/immersiverailroading/model/part/Horn.java, src/main/java/cam72cam/immersiverailroading/model/part/PressureValve.java, src/main/java/cam72cam/immersiverailroading/model/part/StephensonValveGear.java, src/main/java/cam72cam/immersiverailroading/model/part/Whistle.java, src/main/java/cam72cam/immersiverailroading/net/SoundPacket.java, src/main/java/cam72cam/immersiverailroading/registry/EntityRollingStockDefinition.java
The method of creating a new audio effect had a lot of unfortunate copy paste.  It also did not separate attenuation distance by gauge (always)  vs audio pitch scaled by gauge (optional).
Once the basic changes were done, I added a config setting to turn off the gauge pitch scaling as some members had requested it.
=> Refactor sound scale and fix #1302

src/main/java/cam72cam/immersiverailroading/model/part/PartSound.java
My original PR didn't handle the booleans used in the logic for determining start vs loop sound playing individually by stock UUID which caused them to never transition to the idle sound if there were multiple of the same locomotive. Those booleans are now included in the UUID map.
=> Fix bug with multiple locomotives not switching between start sound and loop sound

README.md
[The docs](https://support.curseforge.com/en/support/solutions/articles/9000206928-curseforge-badges) say you can use the project slug, but it appears that no longer works.
=> Fix CurseForge README badges

src/main/java/cam72cam/immersiverailroading/Config.java, src/main/java/cam72cam/immersiverailroading/entity/EntityCoupleableRollingStock.java, src/main/java/cam72cam/immersiverailroading/entity/EntityMoveableRollingStock.java, src/main/java/cam72cam/immersiverailroading/entity/physics/Consist.java, src/main/java/cam72cam/immersiverailroading/entity/physics/Simulation.java, src/main/java/cam72cam/immersiverailroading/entity/physics/SimulationState.java, src/main/java/cam72cam/immersiverailroading/tile/TileRailBase.java, src/main/java/cam72cam/immersiverailroading/track/IIterableTrack.java, src/main/java/cam72cam/immersiverailroading/util/SpawnUtil.java
There are a few pieces to this:
* Tracking consists for chunk loading / dirty flag propagation
* Faster track pathing
* Chunk loading management pre each physics tick calculation.
* Better train placement logic
The most drastic change is that the keepStockLoaded flag should not be critical or even needed to prevent stopped trains from decoupling due to chunk loading issues.
=> Performance changes to server physics simulation

src/main/java/cam72cam/immersiverailroading/track/BuilderBase.java
Made exception to allow break-block placement to clear snow from the specific tiles where the rails are to be built. This solves the existing issue that made creative track building through snowy areas tedious and required manual snow harvesting. Note: This doesn't change any prerequisites for requireSolid.
=> Allow Track Tiles to Build in Snow

src/main/java/cam72cam/immersiverailroading/track/BuilderIterator.java
Manipulated terms in Grade crossing math to reduce chained operations. Symmetrized behavior for positive and negative values of q to make grade crossing heights symmetrical on both sides of track.
=> Fixed Grade Crossing Math

.github/workflows/branch.yml, .github/workflows/main.yml, .github/workflows/release.yml
With the deprecation of v1&v2 workflow at the beginning of 2024, IR's build pipeline had been exist in name only since it used v2.
This PR aims to migrate the build pipeline to modern versions of GH actions in order to recover its function.
=> Chore: update GH actions script to v4

src/main/java/cam72cam/immersiverailroading/ConfigGraphics.java, src/main/java/cam72cam/immersiverailroading/tile/TileRail.java
Add config in ConfigGraphics for track's max render distance instead of hard-coded
=> feat: configuration for track max render distance

src/main/java/cam72cam/immersiverailroading/entity/ClientPartDragging.java
IR doesn't check stock's building status when processing control drag, so users can control an unfinished stock. This this pr fixes that.
=> Fix: Un-built stock can be controlled by dragging

src/main/java/cam72cam/immersiverailroading/gui/TrackGui.java, src/main/java/cam72cam/immersiverailroading/render/multiblock/BoilerRollerRender.java
In default 16:9 screen TrackGUI's left lower panel would cover some of upper panel's elements, this pr improves that by making isPreviewCB and isGradeCrossingCB be on the same line (requires UMC 1.14+ add 1.12-like check box)
=> Fix: TrackGUI element overlapping

src/main/java/cam72cam/immersiverailroading/entity/Locomotive.java, src/main/java/cam72cam/immersiverailroading/entity/LocomotiveDiesel.java
It is reported in #1526 that when using augment to control diesel throttle it will jump between 2 neighbour notches as the code doesn't expect a constant middle value input, and after testing this also happens when player trying to drag them in GUI.
This pr fixes it by using Math.round
=> [Fix] Diesel throttle glitches when trying to set it at a non-notched value

src/main/java/cam72cam/immersiverailroading/gui/PaintBrushPicker.java, src/main/java/cam72cam/immersiverailroading/gui/TrackGui.java, src/main/java/cam72cam/immersiverailroading/gui/components/ListSelector.java, src/main/java/cam72cam/immersiverailroading/items/ItemManual.java, src/main/java/cam72cam/immersiverailroading/items/ItemRadioCtrlCard.java, src/main/java/cam72cam/immersiverailroading/items/ItemTrackBlueprint.java, src/main/java/cam72cam/immersiverailroading/library/ChatText.java, src/main/java/cam72cam/immersiverailroading/library/GuiText.java, src/main/java/cam72cam/immersiverailroading/library/ModelComponentType.java, src/main/java/cam72cam/immersiverailroading/model/part/Control.java, src/main/java/cam72cam/immersiverailroading/multiblock/Multiblock.java, src/main/resources/assets/immersiverailroading/lang/en_us.lang
This PR:
- Adds some new translation keys to replace hard-coded GUI string
- Adds stock names translation keys
- Add a way to translate component label:
- First it will find label.immersiverailroading:[stock type].[json name].[label text]
- If not found it will try label.immersiverailroading:[label text]
- If still not found it will fallback to old code
=> [Feature & I18n] Add translations to hard-coded string

src/main/java/cam72cam/immersiverailroading/entity/EntityRollingStock.java
If corresponding pack is not present, stock will refuse to join the world thus never call `kill()`, resulting in the entity never removed until pack loaded(aka "Ghost stock"). This PR fixes that by calling `kill` in `tryJoinWorld`
=> [Fix] Stock not removed if pack not present
